version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      # Override for Docker networking
      - VECTOR_DB__HOST=qdrant
    depends_on:
      - qdrant
    develop:
      watch:
        - path: ./src/
          target: /app/src/
          action: sync

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7860:7860"
    env_file:
      - .env
    environment:
      # Override for Docker networking
      - BACKEND_URL=http://app:8000
    depends_on:
      - app
    # Gradio can be slow to stop, so we use SIGKILL
    stop_signal: SIGKILL
    develop:
      watch:
        - path: ./src/ai_ethics_assistant/cmds/
          target: /app/src/ai_ethics_assistant/cmds/
          action: sync
    command: ["python", "-m", "ai_ethics_assistant.cmds.gradio_app"]

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  qdrant_data: